import type { Metadata } from "next";
import {  Montserrat } from "next/font/google";
import "./globals.css";

const MontserratFont = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Zustand App",
  description: "Generated by create zustand app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${MontserratFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
